//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.ATInvoice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/", ConfigurationName="Infrastructure.ATInvoice.faturas")]
    public interface faturas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.portaldasfinancas.gov.pt/faturas/RegisterInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Infrastructure.ATInvoice.RegisterInvoiceResponse> RegisterInvoiceAsync(Infrastructure.ATInvoice.RegisterInvoiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class RegisterInvoiceType
    {
        
        private string taxRegistrationNumberField;
        
        private string invoiceNoField;
        
        private System.DateTime invoiceDateField;
        
        private InvoiceType invoiceTypeField;
        
        private InvoiceStatus invoiceStatusField;
        
        private bool invoiceStatusFieldSpecified;
        
        private string eACCodeField;
        
        private object itemField;
        
        private RegisterInvoiceTypeLine[] lineField;
        
        private RegisterInvoiceTypeDocumentTotals documentTotalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string TaxRegistrationNumber
        {
            get
            {
                return this.taxRegistrationNumberField;
            }
            set
            {
                this.taxRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public InvoiceType InvoiceType
        {
            get
            {
                return this.invoiceTypeField;
            }
            set
            {
                this.invoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public InvoiceStatus InvoiceStatus
        {
            get
            {
                return this.invoiceStatusField;
            }
            set
            {
                this.invoiceStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceStatusSpecified
        {
            get
            {
                return this.invoiceStatusFieldSpecified;
            }
            set
            {
                this.invoiceStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EACCode
        {
            get
            {
                return this.eACCodeField;
            }
            set
            {
                this.eACCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerTaxID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("InternationalCustomerTaxID", typeof(InternationalCustomerTaxID), Order=6)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public RegisterInvoiceTypeLine[] Line
        {
            get
            {
                return this.lineField;
            }
            set
            {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public RegisterInvoiceTypeDocumentTotals DocumentTotals
        {
            get
            {
                return this.documentTotalsField;
            }
            set
            {
                this.documentTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public enum InvoiceType
    {
        
        /// <remarks/>
        FT,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        ND,
        
        /// <remarks/>
        FS,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        DC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public enum InvoiceStatus
    {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class InternationalCustomerTaxID
    {
        
        private string taxIDNumberField;
        
        private string taxIDCountryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TaxIDNumber
        {
            get
            {
                return this.taxIDNumberField;
            }
            set
            {
                this.taxIDNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TaxIDCountry
        {
            get
            {
                return this.taxIDCountryField;
            }
            set
            {
                this.taxIDCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class RegisterInvoiceResponseType
    {
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class RegisterInvoiceTypeLine
    {
        
        private OrderReference[] orderReferencesField;
        
        private decimal itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private Tax taxField;
        
        private string taxExemptionReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderReference", IsNullable=false)]
        public OrderReference[] OrderReferences
        {
            get
            {
                return this.orderReferencesField;
            }
            set
            {
                this.orderReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditAmount", typeof(decimal), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("DebitAmount", typeof(decimal), Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Tax Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TaxExemptionReason
        {
            get
            {
                return this.taxExemptionReasonField;
            }
            set
            {
                this.taxExemptionReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class OrderReference
    {
        
        private string originatingONField;
        
        private System.DateTime orderDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OriginatingON
        {
            get
            {
                return this.originatingONField;
            }
            set
            {
                this.originatingONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        CreditAmount,
        
        /// <remarks/>
        DebitAmount,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class Tax
    {
        
        private string taxTypeField;
        
        private string taxCountryRegionField;
        
        private decimal taxPercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TaxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaxCountryRegion
        {
            get
            {
                return this.taxCountryRegionField;
            }
            set
            {
                this.taxCountryRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TaxPercentage
        {
            get
            {
                return this.taxPercentageField;
            }
            set
            {
                this.taxPercentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/")]
    public partial class RegisterInvoiceTypeDocumentTotals
    {
        
        private decimal taxPayableField;
        
        private decimal netTotalField;
        
        private decimal grossTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal TaxPayable
        {
            get
            {
                return this.taxPayableField;
            }
            set
            {
                this.taxPayableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal NetTotal
        {
            get
            {
                return this.netTotalField;
            }
            set
            {
                this.netTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal GrossTotal
        {
            get
            {
                return this.grossTotalField;
            }
            set
            {
                this.grossTotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterInvoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/", Order=0)]
        public Infrastructure.ATInvoice.RegisterInvoiceType RegisterInvoiceElem;
        
        public RegisterInvoiceRequest()
        {
        }
        
        public RegisterInvoiceRequest(Infrastructure.ATInvoice.RegisterInvoiceType RegisterInvoiceElem)
        {
            this.RegisterInvoiceElem = RegisterInvoiceElem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterInvoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicos.portaldasfinancas.gov.pt/faturas/", Order=0)]
        public Infrastructure.ATInvoice.RegisterInvoiceResponseType RegisterInvoiceResponseElem;
        
        public RegisterInvoiceResponse()
        {
        }
        
        public RegisterInvoiceResponse(Infrastructure.ATInvoice.RegisterInvoiceResponseType RegisterInvoiceResponseElem)
        {
            this.RegisterInvoiceResponseElem = RegisterInvoiceResponseElem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface faturasChannel : Infrastructure.ATInvoice.faturas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class faturasClient : System.ServiceModel.ClientBase<Infrastructure.ATInvoice.faturas>, Infrastructure.ATInvoice.faturas
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public faturasClient() : 
                base(faturasClient.GetDefaultBinding(), faturasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.faturasSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public faturasClient(EndpointConfiguration endpointConfiguration) : 
                base(faturasClient.GetBindingForEndpoint(endpointConfiguration), faturasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public faturasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(faturasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public faturasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(faturasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public faturasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infrastructure.ATInvoice.RegisterInvoiceResponse> Infrastructure.ATInvoice.faturas.RegisterInvoiceAsync(Infrastructure.ATInvoice.RegisterInvoiceRequest request)
        {
            return base.Channel.RegisterInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infrastructure.ATInvoice.RegisterInvoiceResponse> RegisterInvoiceAsync(Infrastructure.ATInvoice.RegisterInvoiceType RegisterInvoiceElem)
        {
            Infrastructure.ATInvoice.RegisterInvoiceRequest inValue = new Infrastructure.ATInvoice.RegisterInvoiceRequest();
            inValue.RegisterInvoiceElem = RegisterInvoiceElem;
            return ((Infrastructure.ATInvoice.faturas)(this)).RegisterInvoiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.faturasSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.faturasSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://servicos.portaldasfinancas.gov.pt/faturas/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return faturasClient.GetBindingForEndpoint(EndpointConfiguration.faturasSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return faturasClient.GetEndpointAddress(EndpointConfiguration.faturasSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            faturasSOAP,
        }
    }
}
